"""Canonical registry of implemented agents and lifecycle artifacts."""

AGENT_REGISTRY = [
    {
        "name": "Context Curator",
        "module": "agents.context_curator",
        "entrypoint": "curate_context",
        "permission_symbol": "CONTEXT_CURATOR_PERMISSIONS",
        "lifecycle_doc": "docs/agents/context-curator.md",
        "test_file": "tests/test_context_curator.py",
        "category": "governance",
        "standard_permissions": True,
    },
    {
        "name": "Task Decomposer",
        "module": "agents.task_decomposer",
        "entrypoint": "decompose_requirements",
        "permission_symbol": "TASK_DECOMPOSER_PERMISSIONS",
        "lifecycle_doc": "docs/agents/task-decomposer.md",
        "test_file": "tests/test_task_decomposer.py",
        "category": "meta_agent",
        "standard_permissions": True,
    },
    {
        "name": "Deterministic Validator",
        "module": "agents.deterministic_validator",
        "entrypoint": "validate_output",
        "permission_symbol": "DETERMINISTIC_VALIDATOR_PERMISSIONS",
        "lifecycle_doc": "docs/agents/deterministic-validator.md",
        "test_file": "tests/test_deterministic_validator.py",
        "category": "validator",
        "standard_permissions": True,
    },
    {
        "name": "Surgical Refiner",
        "module": "agents.surgical_refiner",
        "entrypoint": "generate_refinement_feedback",
        "permission_symbol": "SURGICAL_REFINER_PERMISSIONS",
        "lifecycle_doc": "docs/agents/surgical-refiner.md",
        "test_file": "tests/test_surgical_refiner.py",
        "category": "governance",
        "standard_permissions": True,
    },
    {
        "name": "Agent Assigner",
        "module": "agents.agent_assigner",
        "entrypoint": "assign_tasks",
        "permission_symbol": "AGENT_ASSIGNER_PERMISSIONS",
        "lifecycle_doc": "docs/agents/agent-assigner.md",
        "test_file": "tests/test_agent_assigner.py",
        "category": "meta_agent",
        "standard_permissions": True,
    },
    {
        "name": "Domain Dispatcher",
        "module": "agents.domain_dispatcher",
        "entrypoint": "dispatch_domain_tasks",
        "permission_symbol": "DOMAIN_DISPATCHER_PERMISSIONS",
        "lifecycle_doc": "docs/agents/domain-dispatcher.md",
        "test_file": "tests/test_domain_dispatcher.py",
        "category": "orchestration",
        "standard_permissions": True,
    },
    {
        "name": "Graph Execution Orchestrator",
        "module": "agents.graph_execution_orchestrator",
        "entrypoint": "orchestrate_graph_execution",
        "permission_symbol": "GRAPH_EXECUTION_ORCHESTRATOR_PERMISSIONS",
        "lifecycle_doc": "docs/agents/graph-execution-orchestrator.md",
        "test_file": "tests/test_graph_execution_orchestrator.py",
        "category": "orchestration",
        "standard_permissions": True,
    },
    {
        "name": "Progress Monitor",
        "module": "agents.progress_monitor",
        "entrypoint": "monitor_progress",
        "permission_symbol": "PROGRESS_MONITOR_PERMISSIONS",
        "lifecycle_doc": "docs/agents/progress-monitor.md",
        "test_file": "tests/test_progress_monitor.py",
        "category": "meta_agent",
        "standard_permissions": True,
    },
    {
        "name": "Quality Reviewer",
        "module": "agents.quality_reviewer",
        "entrypoint": "review_quality",
        "permission_symbol": "QUALITY_REVIEWER_PERMISSIONS",
        "lifecycle_doc": "docs/agents/quality-reviewer.md",
        "test_file": "tests/test_quality_reviewer.py",
        "category": "meta_agent",
        "standard_permissions": True,
    },
    {
        "name": "Integration Agent",
        "module": "agents.integration_agent",
        "entrypoint": "integrate_artifacts",
        "permission_symbol": "INTEGRATION_AGENT_PERMISSIONS",
        "lifecycle_doc": "docs/agents/integration-agent.md",
        "test_file": "tests/test_integration_agent.py",
        "category": "meta_agent",
        "standard_permissions": True,
    },
    {
        "name": "Decision & Conflict Agent",
        "module": "agents.decision_conflict_agent",
        "entrypoint": "resolve_conflicts",
        "permission_symbol": "DECISION_CONFLICT_PERMISSIONS",
        "lifecycle_doc": "docs/agents/decision-conflict-agent.md",
        "test_file": "tests/test_decision_conflict_agent.py",
        "category": "meta_agent",
        "standard_permissions": True,
    },
    {
        "name": "Resource & Priority Agent",
        "module": "agents.resource_priority_agent",
        "entrypoint": "prioritize_resources",
        "permission_symbol": "RESOURCE_PRIORITY_PERMISSIONS",
        "lifecycle_doc": "docs/agents/resource-priority-agent.md",
        "test_file": "tests/test_resource_priority_agent.py",
        "category": "meta_agent",
        "standard_permissions": True,
    },
    {
        "name": "Human Escalation Agent",
        "module": "agents.human_escalation",
        "entrypoint": "handle_escalation",
        "permission_symbol": "HUMAN_ESCALATION_PERMISSIONS",
        "lifecycle_doc": "docs/agents/human-escalation-agent.md",
        "test_file": "tests/test_human_escalation.py",
        "category": "meta_agent",
        "standard_permissions": True,
    },
    {
        "name": "Code Executor",
        "module": "agents.code_executor",
        "entrypoint": "execute_task",
        "permission_symbol": "CODE_EXECUTOR_PERMISSIONS",
        "lifecycle_doc": "docs/agents/code-executor.md",
        "test_file": "tests/test_code_executor.py",
        "category": "code_generation",
        "standard_permissions": True,
    },
    {
        "name": "Test Runner",
        "module": "agents.test_runner_agent",
        "entrypoint": "run_code_and_tests",
        "permission_symbol": "TEST_RUNNER_PERMISSIONS",
        "lifecycle_doc": "docs/agents/test-runner.md",
        "test_file": "tests/test_test_runner_agent.py",
        "category": "execution",
        "standard_permissions": True,
    },
    {
        "name": "Karpathy Pipeline",
        "module": "agents.karpathy_pipeline",
        "entrypoint": "run_karpathy_pipeline",
        "permission_symbol": None,
        "lifecycle_doc": "docs/agents/karpathy-pipeline.md",
        "test_file": "tests/test_karpathy_pipeline.py",
        "category": "pipeline",
        "standard_permissions": False,
    },
    {
        "name": "Domain Context Managers",
        "module": "agents.domain_context_managers",
        "entrypoint": "BaseDomainContextManager",
        "permission_symbol": None,
        "lifecycle_doc": "docs/agents/domain-context-managers.md",
        "test_file": "tests/test_domain_context_managers.py",
        "category": "context_management",
        "standard_permissions": False,
    },
    {
        "name": "Domain Squad Agents",
        "module": "agents.domain_squads",
        "entrypoint": "AuthSquadAgent",
        "permission_symbol": "SQUAD_PERMISSIONS",
        "lifecycle_doc": "docs/agents/auth-squad-agent.md",
        "test_file": "tests/test_domain_squads.py",
        "category": "domain_squad",
        "standard_permissions": False,
    },
]
