"""Canonical registry of implemented agents and lifecycle artifacts."""

AGENT_REGISTRY = [
    {
        "name": "Context Curator",
        "module": "agents.context_curator",
        "entrypoint": "curate_context",
        "permission_symbol": "CONTEXT_CURATOR_PERMISSIONS",
        "lifecycle_doc": "docs/agents/context-curator.md",
        "test_file": "tests/test_context_curator.py",
        "category": "governance",
        "standard_permissions": True,
    },
    {
        "name": "Task Decomposer",
        "module": "agents.task_decomposer",
        "entrypoint": "decompose_requirements",
        "permission_symbol": "TASK_DECOMPOSER_PERMISSIONS",
        "lifecycle_doc": "docs/agents/task-decomposer.md",
        "test_file": "tests/test_task_decomposer.py",
        "category": "meta_agent",
        "standard_permissions": True,
    },
    {
        "name": "Deterministic Validator",
        "module": "agents.deterministic_validator",
        "entrypoint": "validate_output",
        "permission_symbol": "DETERMINISTIC_VALIDATOR_PERMISSIONS",
        "lifecycle_doc": "docs/agents/deterministic-validator.md",
        "test_file": "tests/test_deterministic_validator.py",
        "category": "validator",
        "standard_permissions": True,
    },
    {
        "name": "Surgical Refiner",
        "module": "agents.surgical_refiner",
        "entrypoint": "generate_refinement_feedback",
        "permission_symbol": "SURGICAL_REFINER_PERMISSIONS",
        "lifecycle_doc": "docs/agents/surgical-refiner.md",
        "test_file": "tests/test_surgical_refiner.py",
        "category": "governance",
        "standard_permissions": True,
    },
    {
        "name": "Agent Assigner",
        "module": "agents.agent_assigner",
        "entrypoint": "assign_tasks",
        "permission_symbol": "AGENT_ASSIGNER_PERMISSIONS",
        "lifecycle_doc": "docs/agents/agent-assigner.md",
        "test_file": "tests/test_agent_assigner.py",
        "category": "meta_agent",
        "standard_permissions": True,
    },
    {
        "name": "Domain Dispatcher",
        "module": "agents.domain_dispatcher",
        "entrypoint": "dispatch_domain_tasks",
        "permission_symbol": "DOMAIN_DISPATCHER_PERMISSIONS",
        "lifecycle_doc": "docs/agents/domain-dispatcher.md",
        "test_file": "tests/test_domain_dispatcher.py",
        "category": "orchestration",
        "standard_permissions": True,
    },
    {
        "name": "Graph Execution Orchestrator",
        "module": "agents.graph_execution_orchestrator",
        "entrypoint": "orchestrate_graph_execution",
        "permission_symbol": "GRAPH_EXECUTION_ORCHESTRATOR_PERMISSIONS",
        "lifecycle_doc": "docs/agents/graph-execution-orchestrator.md",
        "test_file": "tests/test_graph_execution_orchestrator.py",
        "category": "orchestration",
        "standard_permissions": True,
    },
    {
        "name": "Progress Monitor",
        "module": "agents.progress_monitor",
        "entrypoint": "monitor_progress",
        "permission_symbol": "PROGRESS_MONITOR_PERMISSIONS",
        "lifecycle_doc": "docs/agents/progress-monitor.md",
        "test_file": "tests/test_progress_monitor.py",
        "category": "meta_agent",
        "standard_permissions": True,
    },
    {
        "name": "Quality Reviewer",
        "module": "agents.quality_reviewer",
        "entrypoint": "review_quality",
        "permission_symbol": "QUALITY_REVIEWER_PERMISSIONS",
        "lifecycle_doc": "docs/agents/quality-reviewer.md",
        "test_file": "tests/test_quality_reviewer.py",
        "category": "meta_agent",
        "standard_permissions": True,
    },
    {
        "name": "Integration Agent",
        "module": "agents.integration_agent",
        "entrypoint": "integrate_artifacts",
        "permission_symbol": "INTEGRATION_AGENT_PERMISSIONS",
        "lifecycle_doc": "docs/agents/integration-agent.md",
        "test_file": "tests/test_integration_agent.py",
        "category": "meta_agent",
        "standard_permissions": True,
    },
    {
        "name": "Decision & Conflict Agent",
        "module": "agents.decision_conflict_agent",
        "entrypoint": "resolve_conflicts",
        "permission_symbol": "DECISION_CONFLICT_PERMISSIONS",
        "lifecycle_doc": "docs/agents/decision-conflict-agent.md",
        "test_file": "tests/test_decision_conflict_agent.py",
        "category": "meta_agent",
        "standard_permissions": True,
    },
    {
        "name": "Resource & Priority Agent",
        "module": "agents.resource_priority_agent",
        "entrypoint": "prioritize_resources",
        "permission_symbol": "RESOURCE_PRIORITY_PERMISSIONS",
        "lifecycle_doc": "docs/agents/resource-priority-agent.md",
        "test_file": "tests/test_resource_priority_agent.py",
        "category": "meta_agent",
        "standard_permissions": True,
    },
    {
        "name": "Human Escalation Agent",
        "module": "agents.human_escalation",
        "entrypoint": "handle_escalation",
        "permission_symbol": "HUMAN_ESCALATION_PERMISSIONS",
        "lifecycle_doc": "docs/agents/human-escalation-agent.md",
        "test_file": "tests/test_human_escalation.py",
        "category": "meta_agent",
        "standard_permissions": True,
    },
    {
        "name": "Code Executor",
        "module": "agents.code_executor",
        "entrypoint": "execute_task",
        "permission_symbol": "CODE_EXECUTOR_PERMISSIONS",
        "lifecycle_doc": "docs/agents/code-executor.md",
        "test_file": "tests/test_code_executor.py",
        "category": "code_generation",
        "standard_permissions": True,
    },
    {
        "name": "Test Runner",
        "module": "agents.test_runner_agent",
        "entrypoint": "run_code_and_tests",
        "permission_symbol": "TEST_RUNNER_PERMISSIONS",
        "lifecycle_doc": "docs/agents/test-runner.md",
        "test_file": "tests/test_test_runner_agent.py",
        "category": "execution",
        "standard_permissions": True,
    },
    {
        "name": "Karpathy Pipeline",
        "module": "agents.karpathy_pipeline",
        "entrypoint": "run_karpathy_pipeline",
        "permission_symbol": None,
        "lifecycle_doc": "docs/agents/karpathy-pipeline.md",
        "test_file": "tests/test_karpathy_pipeline.py",
        "category": "pipeline",
        "standard_permissions": False,
    },
    {
        "name": "Domain Context Managers",
        "module": "agents.domain_context_managers",
        "entrypoint": "BaseDomainContextManager",
        "permission_symbol": None,
        "lifecycle_doc": "docs/agents/domain-context-managers.md",
        "test_file": "tests/test_domain_context_managers.py",
        "category": "context_management",
        "standard_permissions": False,
    },
    {
        "name": "Domain Squad Agents",
        "module": "agents.domain_squads",
        "entrypoint": "AuthSquadAgent",
        "permission_symbol": "SQUAD_PERMISSIONS",
        "lifecycle_doc": "docs/agents/auth-squad-agent.md",
        "test_file": "tests/test_domain_squads.py",
        "category": "domain_squad",
        "standard_permissions": False,
    },
    # --- New Specialized Agents: AlphaCode + Reflexion inspired (Phase 1) ---
    {
        "name": "Debugger Agent",
        "module": "agents.debugger_agent",
        "entrypoint": "debug_code",
        "permission_symbol": "DEBUGGER_PERMISSIONS",
        "lifecycle_doc": "docs/agents/debugger-agent.md",
        "test_file": "tests/test_debugger_agent.py",
        "category": "repair",
        "standard_permissions": True,
    },
    {
        "name": "Sampling Agent (AlphaCode)",
        "module": "agents.sampling_agent",
        "entrypoint": "sample_candidates",
        "permission_symbol": "SAMPLING_PERMISSIONS",
        "lifecycle_doc": "docs/agents/sampling-agent.md",
        "test_file": "tests/test_sampling_agent.py",
        "category": "generation",
        "standard_permissions": True,
    },
    {
        "name": "Reflexion Agent",
        "module": "agents.reflexion_agent",
        "entrypoint": "generate_reflection",
        "permission_symbol": "REFLEXION_PERMISSIONS",
        "lifecycle_doc": "docs/agents/reflexion-agent.md",
        "test_file": "tests/test_reflexion_agent.py",
        "category": "learning",
        "standard_permissions": True,
    },
    {
        "name": "Competitive Slice Graph",
        "module": "agents.competitive_slice",
        "entrypoint": "run_competitive_slice",
        "permission_symbol": None,
        "lifecycle_doc": "docs/agents/competitive-slice.md",
        "test_file": "tests/test_competitive_slice.py",
        "category": "slice",
        "standard_permissions": False,
    },
    # --- Phase 2: Memory System (Episodic -> Semantic -> Working) ---
    {
        "name": "Episodic Memory Agent",
        "module": "agents.episodic_memory_agent",
        "entrypoint": "store_episode",
        "permission_symbol": "EPISODIC_MEMORY_PERMISSIONS",
        "lifecycle_doc": "docs/agents/episodic-memory-agent.md",
        "test_file": "tests/test_episodic_memory_agent.py",
        "category": "memory",
        "standard_permissions": True,
    },
    {
        "name": "Semantic Memory Agent",
        "module": "agents.semantic_memory_agent",
        "entrypoint": "extract_semantic_rule",
        "permission_symbol": "SEMANTIC_MEMORY_PERMISSIONS",
        "lifecycle_doc": "docs/agents/semantic-memory-agent.md",
        "test_file": "tests/test_semantic_memory_agent.py",
        "category": "memory",
        "standard_permissions": True,
    },
    {
        "name": "Working Memory Agent",
        "module": "agents.working_memory_agent",
        "entrypoint": "assemble_working_memory",
        "permission_symbol": "WORKING_MEMORY_PERMISSIONS",
        "lifecycle_doc": "docs/agents/working-memory-agent.md",
        "test_file": "tests/test_working_memory_agent.py",
        "category": "memory",
        "standard_permissions": True,
    },
    {
        "name": "Competitive Context Manager",
        "module": "agents.competitive_context_manager",
        "entrypoint": "CompetitiveContextManager",
        "permission_symbol": None,
        "lifecycle_doc": "docs/agents/competitive-context-manager.md",
        "test_file": "tests/test_competitive_context_manager.py",
        "category": "context_management",
        "standard_permissions": False,
    },
    {
        "name": "Filtering & Clustering Agent (AlphaCode)",
        "module": "agents.filtering_clustering_agent",
        "entrypoint": "filter_and_cluster",
        "permission_symbol": "FILTERING_CLUSTERING_PERMISSIONS",
        "lifecycle_doc": "docs/agents/filtering-clustering-agent.md",
        "test_file": "tests/test_filtering_clustering_agent.py",
        "category": "generation",
        "standard_permissions": True,
    },
    {
        "name": "Systems Layer (Meta-Loop)",
        "module": "agents.systems_layer",
        "entrypoint": "build_systems_graph",
        "permission_symbol": None,
        "lifecycle_doc": "docs/reconciliation/METHODOLOGY-RECONCILIATION.md",
        "test_file": "tests/test_systems_layer.py",
        "category": "systems_layer",
        "standard_permissions": False,
    },
]
