# version: v1 | 2026-08-08 | verdict: pending-review
"""meta_loop — the gate that makes a digest loop uncloseable until it is real.

Governs the loops declared in `docs/digest/META-LOOP.md`. Fail-closed by design:
a missing artifact is a FAIL, never a silent pass (MEASUREMENT DISCIPLINE — an
apparatus that flatters the system is worse than no apparatus).

Usage:
    python scripts/meta_loop.py inventory <prime-agent-root>   # generate L1 skeleton
    python scripts/meta_loop.py verify L1                      # gate loop 1
    python scripts/meta_loop.py verify L2                      # gate loop 2
    python scripts/meta_loop.py status                         # all gates
"""

from __future__ import annotations

import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DIGEST = REPO / "docs" / "digest"
INVENTORY = DIGEST / "INVENTORY.md"
MECHANISMS = DIGEST / "MECHANISMS.md"
CORRESPONDENCE = DIGEST / "CORRESPONDENCE.md"

MIN_LOC = 100
COVERAGE_TARGET = 0.95

# Directories excluded from the digest scope, with the reason recorded so the
# exclusion is auditable rather than a silent shrink of the denominator.
EXCLUDED = {
    "test": "test suites — behaviour is digested via the source they exercise",
    "node_modules": "vendored dependencies",
    ".git": "vcs metadata",
}
EXCLUDED_FILES = {
    "models.generated.ts": "generated model catalog (20k lines), not hand-written logic",
}
CODE_SUFFIXES = {".ts", ".py", ".md"}


@dataclass(frozen=True)
class SourceFile:
    path: str
    loc: int
    area: str


def _iter_source_files(root: Path) -> list[SourceFile]:
    """All in-scope files >= MIN_LOC, with their area (top-level package)."""
    out: list[SourceFile] = []
    for p in sorted(root.rglob("*")):
        if not p.is_file() or p.suffix not in CODE_SUFFIXES:
            continue
        rel = p.relative_to(root)
        parts = set(rel.parts)
        if parts & EXCLUDED.keys():
            continue
        if p.name in EXCLUDED_FILES:
            continue
        try:
            loc = sum(1 for _ in p.open("r", encoding="utf-8", errors="replace"))
        except OSError:
            continue
        if loc < MIN_LOC:
            continue
        area = "/".join(rel.parts[:2]) if len(rel.parts) > 1 else str(rel)
        out.append(SourceFile(path=str(rel), loc=loc, area=area))
    return out


def cmd_inventory(root: Path) -> int:
    """Generate the L1 inventory skeleton: one row per in-scope file, unfilled."""
    files = _iter_source_files(root)
    by_area: dict[str, list[SourceFile]] = {}
    for f in files:
        by_area.setdefault(f.area, []).append(f)

    lines = [
        "# INVENTORY — prime-agent files >= 100 LOC",
        "",
        f"> Generated by `scripts/meta_loop.py inventory`. Scope: {len(files)} files "
        f">= {MIN_LOC} LOC across {len(by_area)} areas.",
        "> `responsibility` and `verdict` are filled by the digest loop; a row with "
        "either empty FAILS the L1 gate.",
        "> verdict vocabulary: `adopt` | `adapt` | `reject` | `n/a` (with a reason).",
        "",
    ]
    for area in sorted(by_area):
        group = sorted(by_area[area], key=lambda f: -f.loc)
        lines += [
            f"## {area} ({len(group)} files)",
            "",
            "| file | loc | responsibility | verdict |",
            "|---|---:|---|---|",
        ]
        for f in group:
            name = f.path[len(area) + 1 :] if f.path.startswith(area + "/") else f.path
            lines.append(f"| `{name}` | {f.loc} |  |  |")
        lines.append("")

    INVENTORY.parent.mkdir(parents=True, exist_ok=True)
    INVENTORY.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {INVENTORY.relative_to(REPO)}: {len(files)} rows, {len(by_area)} areas")
    return 0


def _parse_inventory_rows() -> list[tuple[str, str, str]]:
    """(file, responsibility, verdict) for every data row in INVENTORY.md."""
    if not INVENTORY.exists():
        return []
    rows: list[tuple[str, str, str]] = []
    for line in INVENTORY.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s.startswith("|") or s.startswith("|---") or s.startswith("| file "):
            continue
        cells = [c.strip() for c in s.strip("|").split("|")]
        if len(cells) != 4:
            continue
        rows.append((cells[0], cells[2], cells[3]))
    return rows


def verify_l1() -> tuple[bool, str]:
    rows = _parse_inventory_rows()
    if not rows:
        return False, "L1 FAIL: INVENTORY.md missing or has no rows"
    filled = [r for r in rows if r[1] and r[2]]
    coverage = len(filled) / len(rows)
    ok = coverage >= COVERAGE_TARGET
    return ok, (
        f"L1 {'PASS' if ok else 'FAIL'}: {len(filled)}/{len(rows)} rows filled "
        f"({coverage:.1%}, target {COVERAGE_TARGET:.0%})"
    )


def _mechanism_ids() -> list[str]:
    """Mechanism ids declared in MECHANISMS.md as `### M<n> — <title>`."""
    if not MECHANISMS.exists():
        return []
    ids = []
    for line in MECHANISMS.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s.startswith("### M") and "—" in s:
            ids.append(s[4:].split("—")[0].strip())
    return ids


def verify_l2() -> tuple[bool, str]:
    mechs = _mechanism_ids()
    if not mechs:
        return False, "L2 FAIL: MECHANISMS.md missing or declares no `### M<n> —` mechanisms"
    if not CORRESPONDENCE.exists():
        return False, "L2 FAIL: CORRESPONDENCE.md missing"
    text = CORRESPONDENCE.read_text(encoding="utf-8")
    missing = [m for m in mechs if m not in text]
    if missing:
        return False, f"L2 FAIL: unmapped mechanisms: {', '.join(missing)}"
    if "TBD" in text:
        return False, "L2 FAIL: CORRESPONDENCE.md still contains TBD"
    return True, f"L2 PASS: {len(mechs)} mechanisms mapped, no TBD"


def verify_l6() -> tuple[bool, str]:
    """Governance: the Constitution must be untouched by the digest work."""
    const = REPO / "CONSTITUTION.md"
    if not const.exists():
        return False, "L6 FAIL: CONSTITUTION.md missing"
    r = subprocess.run(
        ["git", "diff", "--name-only", "HEAD", "--", "CONSTITUTION.md", "LAWS.md"],
        cwd=REPO, capture_output=True, text=True,
    )
    touched = [ln for ln in r.stdout.splitlines() if ln.strip()]
    if touched:
        return False, f"L6 FAIL: authority files modified: {', '.join(touched)}"
    return True, "L6 PASS: CONSTITUTION.md / LAWS.md unmodified"


GATES = {"L1": verify_l1, "L2": verify_l2, "L6": verify_l6}


def cmd_verify(loop: str) -> int:
    gate = GATES.get(loop.upper())
    if gate is None:
        print(f"unknown loop {loop!r}; known: {', '.join(sorted(GATES))}")
        return 2
    ok, msg = gate()
    print(msg)
    return 0 if ok else 1


def cmd_status() -> int:
    worst = 0
    for name in sorted(GATES):
        ok, msg = GATES[name]()
        print(msg)
        worst = worst or (0 if ok else 1)
    return worst


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(__doc__)
        return 2
    cmd = argv[1]
    if cmd == "inventory":
        if len(argv) < 3:
            print("usage: meta_loop.py inventory <prime-agent-root>")
            return 2
        return cmd_inventory(Path(argv[2]).expanduser().resolve())
    if cmd == "verify":
        if len(argv) < 3:
            print("usage: meta_loop.py verify <loop>")
            return 2
        return cmd_verify(argv[2])
    if cmd == "status":
        return cmd_status()
    print(__doc__)
    return 2


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
